version: "3.9"

services:
  ms_loader:
    build:
      context: ./ms_loader
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - ms_net

  ms_stats:
    build:
      context: ./ms_stats
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    networks:
      - ms_net
    depends_on:
      - ms_loader

networks:
  ms_net:
    driver: bridge
